#!/bin/sh

if [ "$ACTION" = "released" ] && [ "$BUTTON" = "wps" -o "$BUTTON" = "reset" ]; then
	if [ "$SEEN" -ge 5 ]; then
		echo "" > /dev/console
		echo "RESET TO FACTORY SETTING EVENT DETECTED" > /dev/console
		echo "PLEASE WAIT WHILE REBOOTING THE DEVICE..." > /dev/console
		rm -rf /overlay/*
		reboot
	fi
fi
